[build]
  publish = "dist/"
  command = "npm run netlify-build"
  functions = "netlify/functions"

# https://docs.netlify.com/configure-builds/file-based-configuration/#functions
[functions]
  # Sets a custom directory for Netlify Functions
  directory = "netlify/functions"

# https://docs.netlify.com/configure-builds/file-based-configuration/#redirects
[[redirects]]
    from = "/tmbd-image*"
    to = "/.netlify/functions/tmdb-image/:splat"
    status = 200

[[redirects]]
    from = "/en/untitled-destin-daniel-cretton-disney-series-198178"
    to = "/en/wonder-man-198178"
    status = 301

[[redirects]]
    from = "/en/marvel-studios-wonder-man-198178"
    to = "/en/wonder-man-198178"
    status = 301

[[redirects]]
    from = "/en/werewolf-by-night-894205"
    to = "/en/untitled-marvel-halloween-special-894205"
    status = 301

[[redirects]]
    from = "/en/captain-america-4-894205"
    to = "/en/captain-america-new-world-order-822119"
    status = 301

[[redirects]]
    from = "/en/agatha-house-of-harkness-138501"
    to = "/en/agatha-coven-of-chaos-138501"
    status = 301

[[redirects]]
    from = "/en/shang-chi-2-912502"
    to = "/en/untitled-shang-chi-sequel-912502"
    status = 301

[[redirects]]
    from = "/en/i-am-groot-207867"
    to = "/en/i-am-groot-209135"
    status = 301

[[redirects]]
    from = "/en/i-am-groot-114469"
    to = "/en/i-am-groot-209135"
    status = 301

[[redirects]]
    from = "/en/marvels-avengers-secret-wars-short-206006"
    to = "/en/marvels-avengers-secret-wars-206006"
    status = 301


# [[redirects]]
#     from = "/en/"
#     to = "/en/"
#     status = 301



